name: captain_drive
description: "A new Flutter project."
publish_to: "none"

version: 1.0.4+9

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # -------------------- ðŸ§± Flutter Core & UI --------------------
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.2
  fluttertoast: ^8.2.8
  modal_progress_hud_nsn: ^0.5.1
  flutter_launcher_icons: ^0.13.1
  flutter_rating_stars: ^1.1.0
  number_paginator: ^0.4.1
  flutter_advanced_switch: ^3.1.0
  carousel_slider: ^4.2.1
  awesome_bottom_bar: ^1.2.4
  material_floating_search_bar_2: ^0.5.0
  flutter_otp_text_field: ^1.1.3+2

  # -------------------- ðŸ”¥ Firebase & Cloud --------------------
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_app_check: ^0.3.2+3
  firebase_messaging: ^15.2.3
  firebase_storage: ^12.4.3
  cloud_firestore: ^5.6.4

  # -------------------- ðŸŒ Location & Maps --------------------
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.6.1
  flutter_polyline_points: ^2.1.0
  location: ^5.0.3
  permission_handler: ^11.3.1

  # -------------------- ðŸ“¡ Networking --------------------
  dio: ^5.7.0
  http: ^1.2.2
  http_parser: ^4.0.2

  # -------------------- ðŸ§  State Management --------------------
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  get_it: ^8.0.0

  # -------------------- ðŸ§© Utilities & Helpers --------------------
  shared_preferences: ^2.3.0
  uuid: ^4.4.0
  intl: ^0.19.0
  email_validator: ^2.1.17
  conditional_builder_null_safety: ^0.0.6
  url_launcher: ^6.3.0

  # -------------------- ðŸ“· Media --------------------
  image_picker: ^1.1.2
  camera: ^0.11.1
  video_player: ^2.9.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/night_map_style.json
    - assets/lang/en.json
    - assets/lang/ar.json

  fonts:
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf

    - family: inter200
      fonts:
        - asset: assets/fonts/Inter-ExtraLight.ttf

    - family: inter700
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
